document: feedback-pipeline-workload
version: 1
data:
  name: MySQL client and server
  description: Client tools and a server daemon for MySQL from Oracle
  maintainer: sst_cs_databases
  packages:
    - mysql8.4
    - mysql8.4-devel
    - mysql8.4-server
    - mysql8.4-test
    - mysql-selinux # because package mysql8.4-server requires (mysql-selinux if selinux-policy-targeted)
    - mecab-ipadic
    - mecab-ipadic-EUCJP
  labels:
    - eln
    - c10s
